[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "myproj-task1"
requires-python = ">=3.7"
version = "1.0"
description = "Namespace tests - tasks"

[tool.flit.module]
name = "myproj.tasks.task1"
