name: Demo

on:
  push:
  pull_request:
  workflow_dispatch: # allow to be run on-demand

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  demo:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        base: ["base/", "-e base/"]
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-cached-uv@v2
      - run: uv venv
      - name: Demonstrate locations and versions of imports
        run: uv run demo.py
