name: Demo

on:
  push:
  pull_request:
  schedule:
    # run monthly on the first day of the month
    - cron: '30 12 1 * *'
  workflow_dispatch: # allow to be run on-demand

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  demo:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        base: ["base/", "-e base/"]
        task1: ["task1/", "-e task1/"]
        # task2 is always fully installed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - run: python -m pip install --upgrade pip
      - run: python -m pip install $BASE $TASK1 ./task2
        env:
          BASE: ${{ matrix.base }}
          TASK1: ${{ matrix.task1 }}
      - name: Demonstrate locations and versions of imports
        run: |
          import myproj
          import myproj.tasks.task1
          import myproj.tasks.task2

          print(myproj)
          print(myproj.__version__)
          print(myproj.tasks.task1)
          print(myproj.tasks.task1.__version__)
          print(myproj.tasks.task2)
          print(myproj.tasks.task2.__version__)
        shell: python
